package com.sitech.po;

import java.util.Date;

public class DmAdpositionidLog2 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_2.id
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_2.monitor_Req
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private String monitorReq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_2.res_id
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private String resId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_2.info
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_2.hour
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private Date hour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_2.DAY
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private Date day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_2.type
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_2.type2
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private String type2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_2.code
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_2.mo
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private String mo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_2.ns
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private String ns;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_2.m1
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private String m1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_2.m2
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private String m2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_2.m3
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private String m3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_2.m1a
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private String m1a;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_2.m2a
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private String m2a;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_2.m9
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private String m9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_2.m9b
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private String m9b;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_2.m1b
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private String m1b;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_2.m1c
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private String m1c;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_2.m9c
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private String m9c;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_2.nx
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private String nx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_2.user_Id
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_2.create_Time
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_2.CID
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private String cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_2.ADID
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private String adid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_2.CRID
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private String crid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_2.Media_Place_Id
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private String mediaPlaceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_2.TS
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private String ts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_2.platform
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private String platform;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_2.id
     *
     * @return the value of dm_adpositionid_log_2.id
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_2.id
     *
     * @param id the value for dm_adpositionid_log_2.id
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_2.monitor_Req
     *
     * @return the value of dm_adpositionid_log_2.monitor_Req
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public String getMonitorReq() {
        return monitorReq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_2.monitor_Req
     *
     * @param monitorReq the value for dm_adpositionid_log_2.monitor_Req
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setMonitorReq(String monitorReq) {
        this.monitorReq = monitorReq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_2.res_id
     *
     * @return the value of dm_adpositionid_log_2.res_id
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public String getResId() {
        return resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_2.res_id
     *
     * @param resId the value for dm_adpositionid_log_2.res_id
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setResId(String resId) {
        this.resId = resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_2.info
     *
     * @return the value of dm_adpositionid_log_2.info
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_2.info
     *
     * @param info the value for dm_adpositionid_log_2.info
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setInfo(String info) {
        this.info = info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_2.hour
     *
     * @return the value of dm_adpositionid_log_2.hour
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public Date getHour() {
        return hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_2.hour
     *
     * @param hour the value for dm_adpositionid_log_2.hour
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setHour(Date hour) {
        this.hour = hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_2.DAY
     *
     * @return the value of dm_adpositionid_log_2.DAY
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public Date getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_2.DAY
     *
     * @param day the value for dm_adpositionid_log_2.DAY
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setDay(Date day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_2.type
     *
     * @return the value of dm_adpositionid_log_2.type
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_2.type
     *
     * @param type the value for dm_adpositionid_log_2.type
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_2.type2
     *
     * @return the value of dm_adpositionid_log_2.type2
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public String getType2() {
        return type2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_2.type2
     *
     * @param type2 the value for dm_adpositionid_log_2.type2
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setType2(String type2) {
        this.type2 = type2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_2.code
     *
     * @return the value of dm_adpositionid_log_2.code
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_2.code
     *
     * @param code the value for dm_adpositionid_log_2.code
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_2.mo
     *
     * @return the value of dm_adpositionid_log_2.mo
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public String getMo() {
        return mo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_2.mo
     *
     * @param mo the value for dm_adpositionid_log_2.mo
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setMo(String mo) {
        this.mo = mo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_2.ns
     *
     * @return the value of dm_adpositionid_log_2.ns
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public String getNs() {
        return ns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_2.ns
     *
     * @param ns the value for dm_adpositionid_log_2.ns
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setNs(String ns) {
        this.ns = ns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_2.m1
     *
     * @return the value of dm_adpositionid_log_2.m1
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public String getM1() {
        return m1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_2.m1
     *
     * @param m1 the value for dm_adpositionid_log_2.m1
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setM1(String m1) {
        this.m1 = m1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_2.m2
     *
     * @return the value of dm_adpositionid_log_2.m2
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public String getM2() {
        return m2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_2.m2
     *
     * @param m2 the value for dm_adpositionid_log_2.m2
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setM2(String m2) {
        this.m2 = m2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_2.m3
     *
     * @return the value of dm_adpositionid_log_2.m3
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public String getM3() {
        return m3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_2.m3
     *
     * @param m3 the value for dm_adpositionid_log_2.m3
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setM3(String m3) {
        this.m3 = m3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_2.m1a
     *
     * @return the value of dm_adpositionid_log_2.m1a
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public String getM1a() {
        return m1a;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_2.m1a
     *
     * @param m1a the value for dm_adpositionid_log_2.m1a
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setM1a(String m1a) {
        this.m1a = m1a;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_2.m2a
     *
     * @return the value of dm_adpositionid_log_2.m2a
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public String getM2a() {
        return m2a;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_2.m2a
     *
     * @param m2a the value for dm_adpositionid_log_2.m2a
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setM2a(String m2a) {
        this.m2a = m2a;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_2.m9
     *
     * @return the value of dm_adpositionid_log_2.m9
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public String getM9() {
        return m9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_2.m9
     *
     * @param m9 the value for dm_adpositionid_log_2.m9
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setM9(String m9) {
        this.m9 = m9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_2.m9b
     *
     * @return the value of dm_adpositionid_log_2.m9b
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public String getM9b() {
        return m9b;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_2.m9b
     *
     * @param m9b the value for dm_adpositionid_log_2.m9b
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setM9b(String m9b) {
        this.m9b = m9b;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_2.m1b
     *
     * @return the value of dm_adpositionid_log_2.m1b
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public String getM1b() {
        return m1b;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_2.m1b
     *
     * @param m1b the value for dm_adpositionid_log_2.m1b
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setM1b(String m1b) {
        this.m1b = m1b;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_2.m1c
     *
     * @return the value of dm_adpositionid_log_2.m1c
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public String getM1c() {
        return m1c;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_2.m1c
     *
     * @param m1c the value for dm_adpositionid_log_2.m1c
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setM1c(String m1c) {
        this.m1c = m1c;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_2.m9c
     *
     * @return the value of dm_adpositionid_log_2.m9c
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public String getM9c() {
        return m9c;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_2.m9c
     *
     * @param m9c the value for dm_adpositionid_log_2.m9c
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setM9c(String m9c) {
        this.m9c = m9c;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_2.nx
     *
     * @return the value of dm_adpositionid_log_2.nx
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public String getNx() {
        return nx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_2.nx
     *
     * @param nx the value for dm_adpositionid_log_2.nx
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setNx(String nx) {
        this.nx = nx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_2.user_Id
     *
     * @return the value of dm_adpositionid_log_2.user_Id
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_2.user_Id
     *
     * @param userId the value for dm_adpositionid_log_2.user_Id
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_2.create_Time
     *
     * @return the value of dm_adpositionid_log_2.create_Time
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_2.create_Time
     *
     * @param createTime the value for dm_adpositionid_log_2.create_Time
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_2.CID
     *
     * @return the value of dm_adpositionid_log_2.CID
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_2.CID
     *
     * @param cid the value for dm_adpositionid_log_2.CID
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setCid(String cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_2.ADID
     *
     * @return the value of dm_adpositionid_log_2.ADID
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public String getAdid() {
        return adid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_2.ADID
     *
     * @param adid the value for dm_adpositionid_log_2.ADID
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setAdid(String adid) {
        this.adid = adid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_2.CRID
     *
     * @return the value of dm_adpositionid_log_2.CRID
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public String getCrid() {
        return crid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_2.CRID
     *
     * @param crid the value for dm_adpositionid_log_2.CRID
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setCrid(String crid) {
        this.crid = crid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_2.Media_Place_Id
     *
     * @return the value of dm_adpositionid_log_2.Media_Place_Id
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public String getMediaPlaceId() {
        return mediaPlaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_2.Media_Place_Id
     *
     * @param mediaPlaceId the value for dm_adpositionid_log_2.Media_Place_Id
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setMediaPlaceId(String mediaPlaceId) {
        this.mediaPlaceId = mediaPlaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_2.TS
     *
     * @return the value of dm_adpositionid_log_2.TS
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public String getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_2.TS
     *
     * @param ts the value for dm_adpositionid_log_2.TS
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setTs(String ts) {
        this.ts = ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_2.platform
     *
     * @return the value of dm_adpositionid_log_2.platform
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_2.platform
     *
     * @param platform the value for dm_adpositionid_log_2.platform
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setPlatform(String platform) {
        this.platform = platform;
    }
}