package com.sitech.po;

import java.util.Date;

public class DmAdpositionidLog1 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_1.id
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_1.monitor_Req
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private String monitorReq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_1.res_id
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private String resId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_1.info
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_1.hour
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private Date hour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_1.DAY
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private Date day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_1.ts
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private String ts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_1.id
     *
     * @return the value of dm_adpositionid_log_1.id
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_1.id
     *
     * @param id the value for dm_adpositionid_log_1.id
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_1.monitor_Req
     *
     * @return the value of dm_adpositionid_log_1.monitor_Req
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public String getMonitorReq() {
        return monitorReq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_1.monitor_Req
     *
     * @param monitorReq the value for dm_adpositionid_log_1.monitor_Req
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setMonitorReq(String monitorReq) {
        this.monitorReq = monitorReq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_1.res_id
     *
     * @return the value of dm_adpositionid_log_1.res_id
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public String getResId() {
        return resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_1.res_id
     *
     * @param resId the value for dm_adpositionid_log_1.res_id
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setResId(String resId) {
        this.resId = resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_1.info
     *
     * @return the value of dm_adpositionid_log_1.info
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_1.info
     *
     * @param info the value for dm_adpositionid_log_1.info
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setInfo(String info) {
        this.info = info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_1.hour
     *
     * @return the value of dm_adpositionid_log_1.hour
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public Date getHour() {
        return hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_1.hour
     *
     * @param hour the value for dm_adpositionid_log_1.hour
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setHour(Date hour) {
        this.hour = hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_1.DAY
     *
     * @return the value of dm_adpositionid_log_1.DAY
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public Date getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_1.DAY
     *
     * @param day the value for dm_adpositionid_log_1.DAY
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setDay(Date day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_1.ts
     *
     * @return the value of dm_adpositionid_log_1.ts
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public String getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_1.ts
     *
     * @param ts the value for dm_adpositionid_log_1.ts
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setTs(String ts) {
        this.ts = ts;
    }
}