package com.sitech.po;

import java.util.Date;

public class DmAdpositionidLog1Custom {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_1.id
     *
     * @mbggenerated Mon Apr 18 17:05:10 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_1.monitor_Req
     *
     * @mbggenerated Mon Apr 18 17:05:10 CST 2016
     */
    private String monitorReq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_1.res_id
     *
     * @mbggenerated Mon Apr 18 17:05:10 CST 2016
     */
    private String res_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_1.info
     *
     * @mbggenerated Mon Apr 18 17:05:10 CST 2016
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_1.DATE
     *
     * @mbggenerated Mon Apr 18 17:05:10 CST 2016
     */
    private Date hour;
    
    private Date day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_adpositionid_log_1.ts
     *
     * @mbggenerated Mon Apr 18 17:05:10 CST 2016
     */
    private String ts;

    private String hourStr;
    
    private String dayStr;
    
    private String tableDateParam;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_1.id
     *
     * @return the value of dm_adpositionid_log_1.id
     *
     * @mbggenerated Mon Apr 18 17:05:10 CST 2016
     */
    public Integer getId() {
        return id;
    }
    
    
    
	public Date getHour() {
		return hour;
	}



	public void setHour(Date hour) {
		this.hour = hour;
	}



	public Date getDay() {
		return day;
	}



	public void setDay(Date day) {
		this.day = day;
	}



	public String getHourStr() {
		return hourStr;
	}



	public void setHourStr(String hourStr) {
		this.hourStr = hourStr;
	}



	public String getDayStr() {
		return dayStr;
	}



	public void setDayStr(String dayStr) {
		this.dayStr = dayStr;
	}



	public String getTableDateParam() {
		return tableDateParam;
	}

	public void setTableDateParam(String tableDateParam) {
		this.tableDateParam = tableDateParam;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_1.id
     *
     * @param id the value for dm_adpositionid_log_1.id
     *
     * @mbggenerated Mon Apr 18 17:05:10 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_1.monitor_Req
     *
     * @return the value of dm_adpositionid_log_1.monitor_Req
     *
     * @mbggenerated Mon Apr 18 17:05:10 CST 2016
     */
    public String getMonitorReq() {
        return monitorReq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_1.monitor_Req
     *
     * @param monitorReq the value for dm_adpositionid_log_1.monitor_Req
     *
     * @mbggenerated Mon Apr 18 17:05:10 CST 2016
     */
    public void setMonitorReq(String monitorReq) {
        this.monitorReq = monitorReq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_1.res_id
     *
     * @return the value of dm_adpositionid_log_1.res_id
     *
     * @mbggenerated Mon Apr 18 17:05:10 CST 2016
     */
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_1.info
     *
     * @return the value of dm_adpositionid_log_1.info
     *
     * @mbggenerated Mon Apr 18 17:05:10 CST 2016
     */
    public String getInfo() {
        return info;
    }

    public String getRes_id() {
		return res_id;
	}

	public void setRes_id(String res_id) {
		this.res_id = res_id;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_1.info
     *
     * @param info the value for dm_adpositionid_log_1.info
     *
     * @mbggenerated Mon Apr 18 17:05:10 CST 2016
     */
    public void setInfo(String info) {
        this.info = info;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_adpositionid_log_1.ts
     *
     * @return the value of dm_adpositionid_log_1.ts
     *
     * @mbggenerated Mon Apr 18 17:05:10 CST 2016
     */
    public String getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_adpositionid_log_1.ts
     *
     * @param ts the value for dm_adpositionid_log_1.ts
     *
     * @mbggenerated Mon Apr 18 17:05:10 CST 2016
     */
    public void setTs(String ts) {
        this.ts = ts;
    }
}