package com.sitech.po;

import java.util.Date;

public class DmReportAdpositionidNumCustom {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_report_adpositionid_num.id
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_report_adpositionid_num.monitor_Req
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private String monitorReq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_report_adpositionid_num.res_id
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private String resId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_report_adpositionid_num.type
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_report_adpositionid_num.num
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private Integer num;
    
    private Integer totalNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_report_adpositionid_num.date
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    private Date day;

    
    private String dayStr;
    
    private String tableDateParam;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_report_adpositionid_num.id
     *
     * @return the value of dm_report_adpositionid_num.id
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_report_adpositionid_num.id
     *
     * @param id the value for dm_report_adpositionid_num.id
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_report_adpositionid_num.monitor_Req
     *
     * @return the value of dm_report_adpositionid_num.monitor_Req
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public String getMonitorReq() {
        return monitorReq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_report_adpositionid_num.monitor_Req
     *
     * @param monitorReq the value for dm_report_adpositionid_num.monitor_Req
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setMonitorReq(String monitorReq) {
        this.monitorReq = monitorReq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_report_adpositionid_num.res_id
     *
     * @return the value of dm_report_adpositionid_num.res_id
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public String getResId() {
        return resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_report_adpositionid_num.res_id
     *
     * @param resId the value for dm_report_adpositionid_num.res_id
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setResId(String resId) {
        this.resId = resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_report_adpositionid_num.type
     *
     * @return the value of dm_report_adpositionid_num.type
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_report_adpositionid_num.type
     *
     * @param type the value for dm_report_adpositionid_num.type
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_report_adpositionid_num.num
     *
     * @return the value of dm_report_adpositionid_num.num
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_report_adpositionid_num.num
     *
     * @param num the value for dm_report_adpositionid_num.num
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    public void setNum(Integer num) {
        this.num = num;
    }

	public Integer getTotalNum() {
		return totalNum;
	}

	public void setTotalNum(Integer totalNum) {
		this.totalNum = totalNum;
	}

	public Date getDay() {
		return day;
	}

	public void setDay(Date day) {
		this.day = day;
	}

	public String getDayStr() {
		return dayStr;
	}

	public void setDayStr(String dayStr) {
		this.dayStr = dayStr;
	}

	public String getTableDateParam() {
		return tableDateParam;
	}

	public void setTableDateParam(String tableDateParam) {
		this.tableDateParam = tableDateParam;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_report_adpositionid_num.date
     *
     * @return the value of dm_report_adpositionid_num.date
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    
}