package com.sitech.dao;

import com.sitech.po.DmAdpositionidLog2;

public interface DmAdpositionidLog2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_adpositionid_log_2
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_adpositionid_log_2
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    int insert(DmAdpositionidLog2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_adpositionid_log_2
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    int insertSelective(DmAdpositionidLog2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_adpositionid_log_2
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    DmAdpositionidLog2 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_adpositionid_log_2
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    int updateByPrimaryKeySelective(DmAdpositionidLog2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_adpositionid_log_2
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    int updateByPrimaryKey(DmAdpositionidLog2 record);
}