package com.sitech.dao;

import com.sitech.po.DmAdpositionidLog1;

public interface DmAdpositionidLog1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_adpositionid_log_1
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_adpositionid_log_1
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    int insert(DmAdpositionidLog1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_adpositionid_log_1
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    int insertSelective(DmAdpositionidLog1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_adpositionid_log_1
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    DmAdpositionidLog1 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_adpositionid_log_1
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    int updateByPrimaryKeySelective(DmAdpositionidLog1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_adpositionid_log_1
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    int updateByPrimaryKey(DmAdpositionidLog1 record);
}