package com.sitech.dao;

import com.sitech.po.DmReportAdpositionidNum;

public interface DmReportAdpositionidNumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_report_adpositionid_num
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_report_adpositionid_num
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    int insert(DmReportAdpositionidNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_report_adpositionid_num
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    int insertSelective(DmReportAdpositionidNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_report_adpositionid_num
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    DmReportAdpositionidNum selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_report_adpositionid_num
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    int updateByPrimaryKeySelective(DmReportAdpositionidNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_report_adpositionid_num
     *
     * @mbggenerated Tue Apr 19 11:01:19 CST 2016
     */
    int updateByPrimaryKey(DmReportAdpositionidNum record);
}